# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  identifier = "home"
  url = "#"
  weight = 10

[[main]]
  name = "About"
  identifier = "about"
  url = "about"
  weight = 20

[[main]]
    name = "Team"
    identifier = "team"
    url = "team"
    weight = 30

[[main]]
    name = "Profiles"
    identifier = "profiles"
    url = "profiles"
    weight = 35
  
#[[main]]
  #name = "Team"
  #url = "team"
  #weight = 30

[[main]]
  name = "BIDWeek2020"
  url = "bidweek2020"
  weight = 40

[[main]]
  name = "Events"
  url = "events"
  weight = 50

[[main]]
  name = "News"
  identifier = "news"
  url = "post"
  weight = 60

[[main]]
  name = "Support"
  identifier = "get-involved"
  url = "get-involved"
  weight = 70

#[[main]]
    #name = "Volunteer"
    #parent = "get-involved"
    #url = "/get-involved/volunteer"
    #weight = 1.0

[[main]]
  name = "Contact"
  url = "contact"
  weight = 80

